# Generated by Django 4.2.7 on 2025-08-03 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='upvotes',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='features.feature')),
            ],
            options={
                'indexes': [models.Index(fields=['feature', 'user_identifier'], name='features_vo_feature_867214_idx')],
                'unique_together': {('feature', 'user_identifier')},
            },
        ),
    ]
